=== silver33255/homework/HW_others/BohdanBoiko/unatrnie-task7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://bank-app.com"
        xmlns:tns="http://bank-app.com"
        elementFormDefault="qualified">
    <element name="bank">
        <complexType>
            <sequence>
                <element name="account" type="tns:account" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="account">
        <sequence>
            <element name="name" type="string"/>
            <element name="id">
                <simpleType>
                    <restriction base="integer">
                        <pattern value="[0-9]{1,10}"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="depositor" type="string"/>
            <element name="country" type="string"/>
            <element name="valet" type="tns:valet" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="valet">
        <all>
            <element name="type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="SAVINGS_BANK_VALET"/>
                        <enumeration value="CURRENT_DEPOSIT_VALET"/>
                        <enumeration value="FIXED_DEPOSIT_VALET"/>
                        <enumeration value="RECURRING_DEPOSIT_VALET"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="amount" type="integer"/>
            <element name="currency">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[A-Z]{3}"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="annualPercentage">
                <simpleType>
                    <restriction base="float">
                        <minInclusive value="0"/>
                        <maxInclusive value="100"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="depositTerm" type="dateTime"/>
        </all>
    </complexType>
</schema>

=== silver33255/homework/HW_others/BohdanBoiko/unatrnie-task7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<bank xmlns="http://bank-app.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://bank-app.com input.xsd">

    <account>
        <name>PUMB</name>
        <id>0000000001</id>
        <depositor>Bohdan Bondarenko</depositor>
        <country>Ukraine</country>
        <valet>
            <type>RECURRING_DEPOSIT_VALET</type>
            <amount>1204</amount>
            <currency>USD</currency>
            <annualPercentage>14</annualPercentage>
            <depositTerm>2020-11-30T12:00:00</depositTerm>
        </valet>
        <valet>
            <type>FIXED_DEPOSIT_VALET</type>
            <amount>544</amount>
            <currency>EUR</currency>
            <annualPercentage>10</annualPercentage>
            <depositTerm>2032-05-06T09:00:00</depositTerm>
        </valet>
        <valet>
            <type>FIXED_DEPOSIT_VALET</type>
            <amount>13643</amount>
            <currency>XCD</currency>
            <annualPercentage>20</annualPercentage>
            <depositTerm>2026-01-03T18:30:00</depositTerm>
        </valet>
    </account>

    <account>
        <name>Alpha Bank</name>
        <id>0000000003</id>
        <depositor>Dmitry Kolesnikov</depositor>
        <country>China</country>
    </account>

    <account>
        <name>OTP Bank</name>
        <id>0000000000</id>
        <depositor>Bohdan Boiko</depositor>
        <country>Ukraine</country>
        <valet>
            <type>CURRENT_DEPOSIT_VALET</type>
            <amount>54</amount>
            <currency>UAH</currency>
            <annualPercentage>5</annualPercentage>
            <depositTerm>2002-05-30T09:00:00</depositTerm>
        </valet>
    </account>
</bank>

=== silver33255/homework/HW_others/BohdanBoiko/unatrnie-task7/output.sax.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<bank xmlns="http://bank-app.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="input.xsd">
    <account>
        <name>PUMB</name>
        <id>1</id>
        <depositor>depositor</depositor>
        <country>Ukraine</country>
        <valet>
            <type>FIXED_DEPOSIT_VALET</type>
            <amount>544</amount>
            <currency>EUR</currency>
            <annualPercentage>10</annualPercentage>
            <depositTerm>2032-05-06T09:00:00</depositTerm>
        </valet>
        <valet>
            <type>RECURRING_DEPOSIT_VALET</type>
            <amount>1204</amount>
            <currency>USD</currency>
            <annualPercentage>14</annualPercentage>
            <depositTerm>2020-11-30T12:00:00</depositTerm>
        </valet>
        <valet>
            <type>FIXED_DEPOSIT_VALET</type>
            <amount>13643</amount>
            <currency>XCD</currency>
            <annualPercentage>20</annualPercentage>
            <depositTerm>2026-01-03T18:30:00</depositTerm>
        </valet>
    </account>
    <account>
        <name>Alpha Bank</name>
        <id>3</id>
        <depositor>depositor</depositor>
        <country>China</country>
    </account>
    <account>
        <name>OTP Bank</name>
        <id>0</id>
        <depositor>depositor</depositor>
        <country>Ukraine</country>
        <valet>
            <type>CURRENT_DEPOSIT_VALET</type>
            <amount>54</amount>
            <currency>UAH</currency>
            <annualPercentage>5</annualPercentage>
            <depositTerm>2002-05-30T09:00:00</depositTerm>
        </valet>
    </account>
</bank>
